name: 'Get & Cached dependencies'
description: 'Get & Cached dependencies'
inputs:
  caching:
    description: Whether cached is required or not
    required: true
    default: 'true'
outputs:
  used-cached:
    description: Whether cached was used or not
    value: ${{ steps.install.outputs.cached }}
runs:
  using: composite
  steps:
    - name: Cached dependencies'
      id: Cached
      uses: actions/cache@v3
      if: inputs.caching == 'true'
      with:
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
        path: node_modules

    - name: Get dependencies'
      id: install
      if: inputs.caching != 'true' || steps.Cached.outputs.cache-hit != 'true'
      run: |
        npm ci
        echo "cached='${{ inputs.caching }}" >> $GITHUB_OUTPUT
      shell: bash