name: "Deploy to AWS S3"
description: "Deploy to AWS S3"
inputs:
  bucket:
    description: "Bucket name"
    required: true
  bucket-region:
    description: "AWS region"
    required: false
    default: "ap-southeast-2"
  dist-folder:
    description: "The folder containing the deployable files"
    required: true
outputs:
  website-url:
    description: "The URL of the deployed bucket"
runs:
  using: "node16"
  main: "main.js"
